
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      name: rasa
      labels:
        app: rasa
    spec:
      imagePullSecrets:
      - name: registry-hub-edisonpark-net
      containers:
      - name: rasa
        imagePullPolicy: Always
        image: hub.edisonpark.net/edisonchat/rasa
        # command: ['rasa', 'run', '--enable-api', '--endpoint', 'endpoints.yml', '--credentials', 'credentials.yml']
        # command: ['python', '-m', 'edo_pro.rasasc', '-r']
        ports:
        - containerPort: 5005
          name: http
          protocol: TCP
        env:
        - name: AppEnv
          value: k8s-prod
---
apiVersion: v1
kind: Service
metadata:
  name: rasa
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5005
    targetPort: 5005
  selector:
    app: rasa