pipeline {
    agent none
    options {
        timeout(time: 10, unit: 'HOURS') 
    }
    stages {
        stage('Prepare Env') {
            agent { 
                docker {
                    image 'hub.edisonpark.net/edisonchat/deploy-helper:2'
                }
            }
            steps {
                // git credentialsId: 'rsa_github', url: 'git@github.com:qianweicheng/rasa.git'
                sh '''
                    pwd
                    python --version
                    ls -al
                '''
            }
        }
        stage('Training') {
            agent {
                docker 'hub.edisonpark.net/edisonchat/rasa:tools' 
            }
            steps {
                sh """
                    python -m edo_pro.rasasc_jeff -t 2>&1
                """
            }
        }
        stage('Build The Image') {
            agent { 
                docker {
                    image 'docker'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            environment {
                EDISON_DOCKER_HUB = credentials('hub.edisonpark.net')
            }
            steps {
                withDockerRegistry(credentialsId: 'hub.edisonpark.net', url: 'https://hub.edisonpark.net/') {
                    sh '''
                        docker build -t hub.edisonpark.net/edisonchat/rasa -f ./deploy/Dockerfile .
                        docker push hub.edisonpark.net/edisonchat/rasa
                        docker tag hub.edisonpark.net/edisonchat/rasa hub.edisonpark.net/edisonchat/rasa:${BUILD_NUMBER}
                        docker push hub.edisonpark.net/edisonchat/rasa:${BUILD_NUMBER}
                    '''
                }
            }
        }
        stage('Deploy to K8S') {
            agent { 
                docker {
                    image 'hub.edisonpark.net/edisonchat/deploy-helper:2'
                }
            }
            steps {
                sh '''
                    # workingspack is rasa
                    # make stag as default
                    # kubectl --kubeconfig /root/kube_config_stag get pod
                    mkdir /root/.kube
                    cp /root/kube_config_stag /root/.kube/config
                '''
                sh '''
                    # TODO: need to replace the version in deployment.yaml
                    application=$(kubectl get deploy rasa | wc -l)
                    if [ $application -eq 2 ];then
                        kubectl set env deploy/rasa version="${BUILD_TAG}"
                    else
                        kubectl apply -f ./deploy/deployment.yaml
                        kubectl apply -f ./deploy/service.yaml
                    fi
                '''
            }
        } 
   }
   post { 
        always {
            emailext body: '''$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

Check console output at $BUILD_URL to view the details.''', subject: 'New Service[$PROJECT_NAME] Deployed!', to: 'chat.alarm@edison.tech,weicheng@edison.tech,lida@edison.tech,songzhou@edison.tech'
        }
    }
}